name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: 213.163.192.71
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/steto
            git pull origin main || git clone https://github.com/azrahudaya/steto.git .
            docker compose pull || true
            docker compose up -d --build
            docker system prune -f
